"""
Builds games/worm/brockton_bay.wrld from the sources in this folder - entirely through the Kuznya MCP server.

Every script, place, prefab and character is created with the same MCP tools an AI agent uses
(script_create, object_create, character_create, server_settings, web_client_set, asset_export).

    pip install mcp
    python games/worm/build.py
"""
import asyncio
import json
import sys
from pathlib import Path

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
sys.path.insert(0, str(HERE / 'data'))
import city_data  # noqa: E402

WORLD = HERE / 'brockton_bay.wrld'
RESEARCH = json.loads((HERE / 'data' / 'canon_research.json').read_text(encoding='utf-8'))
OBJECT_SCRIPTS = {'Director', 'Person', 'Business', 'Player'}
CITY = '/Brockton Bay'


def wikipowers_script():
    examples = [{'cape': e['cape'], 'cls': e['cls'], 'rating': int(e['rating']), 'summary': e['summary'],
                 'tier': e['tier']} for e in RESEARCH['power_examples']]
    classes = [{'cls': c['cls'], 'definition': c['definition'], 'typical_triggers': c['typical_triggers']}
               for c in RESEARCH['power_classes']]
    return ('"""wikipowers: parahuman powers and classifications as listed on the Worm wiki (worm.fandom.com).\n'
            'Generated by build.py from data/canon_research.json; summaries are paraphrased."""\n'
            f'EXAMPLES = {json.dumps(examples, ensure_ascii=False, indent=1)}\n'
            f'CLASSES = {json.dumps(classes, ensure_ascii=False, indent=1)}\n')


def locations():
    described = {entry['name'].lower(): entry['description'] for entry in RESEARCH['locations']}
    built = []
    for name, district, tags, exits, text, extra in city_data.LOCATIONS:
        extra = dict(extra)
        canon_name = extra.pop('canon', name)
        attributes = {'kind': 'location', 'district': district, 'tags': tags, 'exits': exits,
                      'desc': text or described.get(canon_name.lower(), '')}
        if not attributes['desc']:
            raise SystemExit(f'no description for {name}')
        attributes.update(extra)
        built.append({'parent': CITY, 'name': name, 'attributes': attributes,
                      'scripts': ['Business'] if 'biz' in extra else []})
    return built


def characters():
    """(name, location, description, attributes) for every canon cape and civilian."""
    people = []
    for cape in RESEARCH['capes']:
        life = dict(city_data.FACTION_LIVES.get(cape['faction'], city_data.FACTION_LIVES['Independent']))
        life.update(city_data.CAPE_LIVES.get(cape['cape'], {}))
        raw = {'cape': cape['cape'], 'align': life.pop('align', cape['alignment']),
               'lethal': bool(cape.get('lethal')), 'classes': cape['classes'], 'power': cape['power'],
               'look': f"{cape['gear']}" if cape.get('gear') else 'a parahuman in costume'}
        for key in ('passive', 'duty', 'beat', 'base'):
            if key in life:
                raw[key] = life.pop(key)
        attributes = {'kind': 'npc', 'sex': cape['sex'], 'age': cape['age'], 'job': life['job'],
                      'work': life.get('work', ''), 'home': life['home'],
                      'faction': '' if cape['faction'] == 'Independent' else cape['faction'],
                      'family': life.get('family', []), 'cape_raw': raw}
        if 'arrives' in life:
            attributes['arrives'] = life['arrives']
        name = cape.get('civilian') or ''
        if not name:
            name = f"({cape['cape']})"
            attributes['anon'] = True
        where = '/Out of Town' if 'arrives' in life else f"{CITY}/{life['home']}"
        people.append((name, where, f"{cape['civilian_job']}. {', '.join(cape['personality'])}.", attributes))
    for person in RESEARCH['civilians']:
        if person['name'] in city_data.SKIP_CIVILIANS:
            continue
        job, work, home, family = city_data.CIVILIAN_LIVES[person['name']]
        attributes = {'kind': 'npc', 'sex': person['sex'], 'age': person['age'], 'job': job, 'work': work,
                      'home': home, 'family': family}
        name = person['name']
        if "'s " in name:
            attributes['anon'] = True
            name = f"({name})"
        people.append((name, f"{CITY}/{home}", person['notes'], attributes))
    return people


async def build():
    parameters = StdioServerParameters(command=sys.executable, args=[str(ROOT / 'src' / 'mcp_server.py')])
    async with stdio_client(parameters) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            async def call(tool, **arguments):
                result = await session.call_tool(tool, arguments)
                text = result.content[0].text
                failed = result.is_error if hasattr(result, 'is_error') else result.isError
                if failed:
                    raise SystemExit(f'{tool} failed: {text}')
                try:
                    return json.loads(text)
                except ValueError:
                    return text

            await call('world_new', path=str(WORLD), overwrite=True)

            # -- scripts: libraries first, then the four that get attached to objects
            sources = {path.stem: path.read_text(encoding='utf-8') for path in sorted((HERE / 'scripts').glob('*.py'))}
            sources['wikipowers'] = wikipowers_script()
            for name, code in sources.items():
                await call('script_create', name=name, code=code)
            print(f'scripts: {len(sources)}')

            # -- the scene
            await call('object_create', name='Simulation', scripts=['Director'],
                       attributes={'tick_seconds': 2.0, 'about': 'Simulation state lives in these attributes.'})
            await call('object_create', name='Offline Players')
            await call('object_create', name='Out of Town')
            await call('object_create', name='Brockton Bay', attributes={'kind': 'city'})
            places = locations()
            await call('object_create_many', objects=places)
            print(f'places: {len(places)}')

            # -- prefabs
            await call('character_create', name='Player', playable=True, scripts=['Player'],
                       description='A newcomer to Brockton Bay.', attributes={'kind': 'login'})
            await call('object_create', name='Citizen', prefab=True, scripts=['Person'],
                       attributes={'kind': 'npc',
                                   'description': 'A generated resident; the simulation fills in the rest.'})

            # -- canon characters
            cast = characters()
            for name, where, description, attributes in cast:
                await call('character_create', name=name, location=where, description=description,
                           attributes=attributes, scripts=['Person'])
            print(f'characters: {len(cast)}')

            await call('web_client_set', code=(HERE / 'client.html').read_text(encoding='utf-8'))
            await call('server_settings', port_wss=1337, port_web=1339, host='localhost')

            # -- parts of this game as assets other projects can load
            assets = ROOT / 'assets'
            await call('asset_export', kind='script', target='economy', path=str(assets / 'economy.kasset'),
                       author='alexteter-dev',
                       description='Scarcity pricing, production chains, wages and hauling orders for businesses.')
            await call('asset_export', kind='script', target='powers', path=str(assets / 'parahuman_powers.kasset'),
                       author='alexteter-dev',
                       description='Procedural superpower generator over the twelve PRT classifications.')
            await call('asset_export', kind='object', target='prefab:/Citizen', path=str(assets / 'citizen.kasset'),
                       author='alexteter-dev',
                       description='A simulated resident with needs, a job, a task queue and the whole decision loop.')
            info = await call('world_info')
            print(json.dumps(info, ensure_ascii=False))


if __name__ == '__main__':
    asyncio.run(build())
