"""powerdata: tables behind the procedural power generator.

The twelve PRT classifications, archetypes inside each class, themes, drawbacks, and hand-tuned
ability sets for canon capes. Classification definitions follow the Worm wiki's "Power Classifications".
"""

# What each ability does lives in the 'combat' script; this is the text shown to players.
ABILITIES = {
    'blast': 'ranged attack that hits hard',
    'smash': 'a crushing close-range blow',
    'area': 'hits every enemy around you',
    'shield': 'raises a defence for a few moments',
    'swarm': 'sets a swarm on all enemies: damage over time, and they fight half-blind',
    'minions': 'calls minions that fight beside you and take hits for you',
    'dark': 'blinds enemies; you and your allies can slip away',
    'blink': 'instant escape; outside a fight, travel to a nearby place at once',
    'fly': 'escape any fight; outside a fight, travel anywhere in the city at once',
    'phase': 'become untouchable for a moment',
    'heal': 'mend wounds, your own or someone else\'s',
    'freeze': 'lock a target in place',
    'insight': 'read a person: identity, power, state, intentions',
    'craft': 'build a piece of tinkertech from scrap or tools',
    'copy': 'borrow the strength of the strongest parahuman nearby',
    'null': 'switch off a target\'s power for a while',
    'vanish': 'drop out of everyone\'s notice',
    'command': 'take control of an ordinary person',
    'aura': 'a wave of terror: the fainthearted run',
    'morph': 'shift into a stronger form for a while',
}
PASSIVES = {
    'regen': 'wounds close on their own',
    'ramp': 'grows stronger the longer a fight lasts',
    'fast': 'strikes twice as often',
    'tough': 'shrugs off weak attacks',
    'precog': 'sees blows coming and sidesteps them',
    'reroll': 'once per fight, a lost fight "did not happen"',
    'clones': 'half of all attacks hit a copy instead',
    'immortal': 'resets to unharmed every few moments',
    'flight': 'always able to disengage',
}

# cls, key, abilities, passives, weights (atk, dfn, mob, hp), description template
ARCHETYPES = [
    ('Mover', 'teleporter', ['blink'], [], (0.4, 0.2, 1.4, 0.2), 'You step from one place to another without crossing the space between, {theme_how}.'),
    ('Mover', 'flier', ['fly'], ['flight'], (0.5, 0.2, 1.3, 0.2), 'You fly, {theme_how}.'),
    ('Mover', 'speedster', ['blink'], ['fast'], (0.7, 0.3, 1.5, 0.2), 'The world slows to a crawl around you when you run, {theme_how}.'),
    ('Shaker', 'field', ['area', 'shield'], [], (0.9, 0.5, 0.2, 0.3), 'You fill the space around you with {theme}, shaping it at will.'),
    ('Shaker', 'smother', ['dark', 'area'], [], (0.6, 0.6, 0.4, 0.3), 'You flood an area with {theme} that leaves others blind and lost.'),
    ('Shaker', 'terrain', ['area', 'freeze'], [], (0.8, 0.5, 0.2, 0.4), 'You bend the ground and walls around you, raising {theme} wherever you look.'),
    ('Brute', 'juggernaut', ['smash'], ['tough'], (1.0, 1.1, 0.1, 1.2), 'Your body is sheathed in {theme}; you hit like a truck and barely feel what hits back.'),
    ('Brute', 'regenerator', ['smash'], ['regen'], (0.8, 0.6, 0.2, 1.3), 'You heal almost as fast as you are hurt, {theme_how}.'),
    ('Brute', 'escalator', ['smash'], ['ramp', 'regen'], (0.8, 0.7, 0.2, 1.0), 'The longer a fight lasts the bigger, tougher and angrier you get, wreathed in {theme}.'),
    ('Breaker', 'ghost', ['phase'], [], (0.6, 0.5, 0.8, 0.4), 'You turn into a living form of {theme}; in that state ordinary rules do not apply to you.'),
    ('Breaker', 'charged', ['smash', 'shield'], ['fast'], (0.9, 0.6, 0.7, 0.4), 'You store up {theme} while standing still and spend it in bursts of impossible strength.'),
    ('Master', 'swarm', ['swarm', 'insight'], [], (0.8, 0.2, 0.2, 0.2), 'You control {theme} within several blocks, sense through them and direct every one at once.'),
    ('Master', 'beasts', ['minions'], [], (0.7, 0.4, 0.4, 0.3), 'You turn ordinary animals into monstrous {theme} that obey you.'),
    ('Master', 'projection', ['minions', 'area'], [], (0.8, 0.3, 0.2, 0.2), 'You create semi-real soldiers of {theme} that fight for you.'),
    ('Master', 'puppeteer', ['command', 'freeze'], [], (0.3, 0.2, 0.3, 0.2), 'You seize the nerves or minds of people near you, {theme_how}.'),
    ('Master', 'emotion', ['aura', 'command'], [], (0.4, 0.3, 0.2, 0.2), 'People near you feel what you want them to feel, {theme_how}.'),
    ('Tinker', 'armorer', ['craft', 'blast'], [], (0.8, 0.8, 0.3, 0.4), 'You understand how to build things nobody else could; your specialty is {theme}.'),
    ('Tinker', 'bombs', ['craft', 'area'], [], (1.1, 0.2, 0.2, 0.2), 'You build devices that should not work; your specialty is {theme}.'),
    ('Blaster', 'beam', ['blast'], [], (1.2, 0.2, 0.3, 0.2), 'You fire bolts of {theme} from your hands.'),
    ('Blaster', 'artillery', ['blast', 'area'], [], (1.3, 0.1, 0.2, 0.2), 'You throw {theme} that bursts on impact.'),
    ('Blaster', 'conjurer', ['blast', 'shield'], [], (1.0, 0.5, 0.2, 0.2), 'You call up weapons made of {theme}, any shape you can picture.'),
    ('Thinker', 'intuition', ['insight'], ['precog'], (0.3, 0.3, 0.3, 0.1), 'You look at something and simply know things about it, {theme_how}.'),
    ('Thinker', 'precog', ['insight'], ['precog', 'reroll'], (0.4, 0.4, 0.3, 0.1), 'You glimpse what is about to happen, {theme_how}.'),
    ('Thinker', 'skills', ['insight'], ['fast'], (0.8, 0.4, 0.5, 0.2), 'You pick up any skill you watch for a moment, {theme_how}.'),
    ('Striker', 'touch', ['freeze', 'smash'], [], (0.9, 0.3, 0.4, 0.3), 'Whatever you touch is caught in {theme}.'),
    ('Striker', 'healer', ['heal'], [], (0.2, 0.2, 0.2, 0.3), 'With a touch you reshape living tissue, {theme_how}.'),
    ('Striker', 'edge', ['smash'], ['fast'], (1.2, 0.3, 0.5, 0.3), 'Your hands and anything you hold cut through matter like {theme}.'),
    ('Changer', 'beast', ['morph'], ['tough'], (0.9, 0.7, 0.4, 0.8), 'You reshape your body into a creature of {theme}.'),
    ('Changer', 'shifter', ['morph', 'vanish'], [], (0.6, 0.4, 0.6, 0.5), 'You can wear other shapes and faces, {theme_how}.'),
    ('Trump', 'mimic', ['copy'], [], (0.5, 0.5, 0.4, 0.4), 'You borrow the powers of parahumans near you, {theme_how}.'),
    ('Trump', 'nullifier', ['null', 'smash'], [], (0.6, 0.6, 0.3, 0.4), 'Powers gutter and fail around you, {theme_how}.'),
    ('Trump', 'granter', ['heal', 'shield'], [], (0.3, 0.6, 0.3, 0.3), 'You hand out small powers to others for a while, {theme_how}.'),
    ('Stranger', 'unseen', ['vanish'], [], (0.7, 0.3, 0.8, 0.2), 'People stop noticing you, {theme_how}.'),
    ('Stranger', 'forgotten', ['vanish', 'insight'], [], (0.5, 0.3, 0.7, 0.2), 'People forget you the moment they look away, {theme_how}.'),
]

# theme, 'how' phrase, cape-name pool
THEMES = [
    ('insects', 'carried by a cloud of gnats', ['Hive', 'Locust', 'Chitin', 'Mantis', 'Brood']),
    ('rats', 'with a rustle of small claws', ['Piper', 'Vermin', 'Gnaw']),
    ('crows', 'in a storm of black feathers', ['Murder', 'Rook', 'Corvid']),
    ('fire', 'trailing sparks', ['Cinder', 'Kiln', 'Backdraft', 'Ember']),
    ('ice', 'leaving frost behind', ['Rime', 'Hoarfrost', 'Glacier']),
    ('lightning', 'with a crack of static', ['Arc', 'Voltaic', 'Stormcell']),
    ('steel blades', 'with a shriek of metal', ['Razorwire', 'Burr', 'Shiv']),
    ('rust', 'leaving flakes of rust', ['Corrode', 'Oxide', 'Tetanus']),
    ('glass', 'with a sound like breaking windows', ['Shard', 'Pane', 'Crystalline']),
    ('concrete', 'with a grinding of stone', ['Rebar', 'Bulwark', 'Slab']),
    ('seawater', 'smelling of brine', ['Undertow', 'Riptide', 'Brine']),
    ('fog', 'in a curl of mist', ['Haze', 'Pall', 'Murk']),
    ('darkness', 'as the light dims', ['Umbra', 'Blackout', 'Gloom']),
    ('hard light', 'in a flare of colour', ['Prism', 'Halo', 'Lumen']),
    ('sound', 'with a pressure in the ears', ['Tinnitus', 'Klaxon', 'Dirge']),
    ('gravity', 'as your stomach lurches', ['Plummet', 'Freefall', 'Ballast']),
    ('time', 'between one tick of the clock and the next', ['Hourglass', 'Stopwatch', 'Lapse']),
    ('space', 'as distances fold', ['Vanishing Point', 'Fold', 'Parallax']),
    ('bone', 'with a wet crack', ['Ossuary', 'Marrow', 'Carapace']),
    ('blood', 'with the taste of copper', ['Hemlock', 'Clot', 'Sanguine']),
    ('acid', 'with a sharp chemical reek', ['Caustic', 'Etch', 'Solvent']),
    ('smoke', 'in a twist of soot', ['Flue', 'Smolder', 'Ashfall']),
    ('wind', 'with a sudden gust', ['Gale', 'Zephyr', 'Squall']),
    ('plants', 'as weeds push through the cracks', ['Bramble', 'Thistle', 'Kudzu']),
    ('paper', 'in a flutter of pages', ['Origami', 'Folio', 'Ream']),
    ('cloth', 'with a snap of fabric', ['Seamstress', 'Tatter', 'Bolt']),
    ('scrap metal', 'with a clatter of junk', ['Jalopy', 'Heap', 'Salvage']),
    ('magnetism', 'as every loose nail turns toward you', ['Lodestone', 'Polarity', 'Ferrous']),
    ('radiation', 'with a prickle on the skin', ['Halflife', 'Geiger', 'Isotope']),
    ('fear', 'with a cold drop in the gut', ['Dread', 'Phobos', 'Shudder']),
    ('pain', 'with a wince', ['Wince', 'Agony Aunt', 'Throb']),
    ('dreams', 'as if half asleep', ['Somnus', 'Lucid', 'Reverie']),
    ('numbers', 'as the odds line up in your head', ['Abacus', 'Tally', 'Quotient']),
    ('lies', 'hearing what is left unsaid', ['Tell', 'Perjury', 'Subtext']),
    ('machines', 'with a hum of servos', ['Gearbox', 'Flywheel', 'Chassis']),
    ('explosives', 'with the smell of cordite', ['Fuse', 'Primer', 'Detcord']),
    ('ink', 'in a spreading stain', ['Blot', 'Quill', 'Smudge']),
    ('salt', 'with a dry sting', ['Brackish', 'Halite', 'Lot']),
    ('mirrors', 'in a flicker of reflections', ['Looking Glass', 'Facet', 'Doppel']),
    ('wax', 'with a soft drip', ['Tallow', 'Wick', 'Effigy']),
]

# Low rolls get one of these stuck on; they are the "trash" powers.
JOKES = [
    'It only works while you hold your breath.',
    'It only works on things smaller than a shoebox.',
    'It gives you a splitting headache every single time.',
    'It only works while someone is watching you.',
    'It stops working if you eat anything but bread.',
    'It works, but everything you affect turns faintly orange.',
    'It only works on Tuesdays and for about an hour on Sundays.',
    'It makes a noise like a kazoo. Loudly.',
]
DRAWBACKS = [
    'Using it leaves you starving.',
    'It frays your temper; you start fights you should walk away from.',
    'It never fully switches off.',
    'You feel everything your power touches.',
    'It hurts you a little every time.',
    'It is conspicuous: anyone nearby knows a parahuman is at work.',
    'You lose track of people while it is running.',
    '',
    '',
    '',
]

# rating -> weight. Most triggers are street level; a few are monsters.
RATING_WEIGHTS = [(1, 7), (2, 13), (3, 18), (4, 18), (5, 15), (6, 11), (7, 8), (8, 5), (9, 3), (10, 1.5), (12, 0.5)]

# What kind of danger produces what class (Worm wiki, "Trigger Event").
TRIGGER_CLASSES = {
    'beaten': [('Brute', 4), ('Striker', 2), ('Changer', 2), ('Breaker', 1)],
    'outnumbered': [('Master', 3), ('Shaker', 3), ('Blaster', 2), ('Brute', 1)],
    'trapped': [('Mover', 4), ('Breaker', 2), ('Stranger', 2)],
    'ranged': [('Blaster', 3), ('Shaker', 2), ('Mover', 1)],
    'starving': [('Tinker', 3), ('Thinker', 3), ('Master', 1)],
    'witness': [('Trump', 3), ('Thinker', 2), ('Stranger', 1)],
    'hunted': [('Stranger', 3), ('Mover', 2), ('Thinker', 1)],
    'disaster': [('Shaker', 3), ('Brute', 2), ('Mover', 2), ('Breaker', 1)],
}

# Canon capes: abilities, passives, weights (atk, dfn, mob, hp). Ratings and descriptions come from the
# research data; anyone not listed here gets a kit from their primary classification.
CANON = {
    'Armsmaster': (['blast', 'freeze', 'craft'], ['tough'], (1.0, 1.0, 0.5, 0.6)),
    'Miss Militia': (['blast', 'area'], [], (1.4, 0.3, 0.4, 0.3)),
    'Assault': (['smash'], ['fast', 'tough'], (1.0, 0.8, 0.8, 0.4)),
    'Battery': (['smash', 'shield'], ['fast'], (1.1, 0.7, 0.9, 0.5)),
    'Velocity': (['blink'], ['fast', 'flight'], (0.3, 0.4, 1.6, 0.2)),
    'Triumph': (['blast', 'area'], ['tough'], (1.1, 0.5, 0.3, 0.6)),
    'Dauntless': (['blast', 'shield'], ['flight'], (1.1, 0.9, 0.7, 0.4)),
    'Aegis': (['smash', 'fly'], ['immortal', 'flight'], (0.8, 0.6, 0.6, 1.0)),
    'Clockblocker': (['freeze'], [], (0.4, 0.4, 0.3, 0.3)),
    'Gallant': (['blast', 'aura'], ['tough'], (0.8, 0.8, 0.2, 0.4)),
    'Kid Win': (['blast', 'fly', 'craft'], [], (1.0, 0.4, 0.7, 0.3)),
    'Vista': (['freeze', 'shield', 'blink'], [], (0.4, 0.9, 0.9, 0.2)),
    'Shadow Stalker': (['phase', 'blast'], ['flight'], (0.9, 0.5, 0.9, 0.3)),
    'Browbeat': (['smash', 'morph'], ['regen'], (0.9, 0.7, 0.3, 0.9)),
    'Lady Photon': (['blast', 'shield', 'fly'], ['flight'], (1.0, 0.8, 0.7, 0.3)),
    'Manpower': (['smash', 'shield'], ['tough'], (1.0, 0.9, 0.3, 0.9)),
    'Laserdream': (['blast', 'shield', 'fly'], ['flight'], (1.1, 0.6, 0.7, 0.3)),
    'Shielder': (['shield', 'blast', 'fly'], ['flight'], (0.6, 1.2, 0.6, 0.3)),
    'Brandish': (['smash', 'phase'], [], (1.2, 0.4, 0.4, 0.3)),
    'Flashbang': (['area'], [], (1.1, 0.2, 0.2, 0.3)),
    'Glory Girl': (['smash', 'aura', 'fly'], ['tough', 'flight'], (1.1, 1.2, 0.8, 0.6)),
    'Panacea': (['heal'], [], (0.1, 0.1, 0.1, 0.2)),
    'Kaiser': (['area', 'shield', 'freeze'], ['tough'], (1.2, 1.0, 0.2, 0.5)),
    'Purity': (['blast', 'area', 'fly'], ['flight'], (1.5, 0.5, 0.8, 0.4)),
    'Hookwolf': (['morph', 'smash'], ['tough', 'regen'], (1.2, 1.1, 0.5, 1.1)),
    'Krieg': (['shield', 'smash'], ['tough'], (0.9, 1.2, 0.2, 0.7)),
    'Fenja': (['morph', 'smash'], ['tough'], (1.1, 1.2, 0.3, 1.2)),
    'Menja': (['morph', 'smash'], ['tough'], (1.1, 1.2, 0.3, 1.2)),
    'Rune': (['area', 'fly'], ['flight'], (1.0, 0.4, 0.6, 0.3)),
    'Othala': (['heal', 'shield'], [], (0.2, 0.5, 0.2, 0.3)),
    'Victor': (['blast', 'insight'], ['fast'], (1.1, 0.4, 0.5, 0.3)),
    'Alabaster': (['smash'], ['immortal'], (0.7, 0.3, 0.3, 0.5)),
    'Night': (['morph', 'vanish'], ['fast'], (1.4, 0.6, 1.0, 0.6)),
    'Fog': (['dark', 'phase'], [], (0.7, 0.9, 0.4, 0.4)),
    'Crusader': (['minions', 'fly'], [], (1.0, 0.5, 0.4, 0.3)),
    'Cricket': (['smash', 'dark'], ['fast', 'precog'], (1.1, 0.4, 0.8, 0.4)),
    'Stormtiger': (['blast', 'smash'], ['precog'], (1.1, 0.5, 0.6, 0.4)),
    'Lung': (['smash', 'area'], ['ramp', 'regen', 'tough'], (1.0, 0.9, 0.3, 1.1)),
    'Oni Lee': (['blink', 'area'], ['clones'], (1.0, 0.3, 1.3, 0.3)),
    'Bakuda': (['area', 'freeze', 'craft'], [], (1.5, 0.2, 0.2, 0.2)),
    'Skidmark': (['area'], [], (0.7, 0.5, 0.5, 0.3)),
    'Squealer': (['craft', 'smash'], ['tough'], (1.0, 1.0, 0.8, 0.5)),
    'Mush': (['morph'], ['tough'], (0.9, 1.0, 0.2, 0.9)),
    'Whirlygig': (['area'], [], (0.9, 0.4, 0.2, 0.3)),
    'Grue': (['dark', 'smash'], [], (0.8, 0.6, 0.4, 0.5)),
    'Tattletale': (['insight'], ['precog'], (0.3, 0.2, 0.4, 0.2)),
    'Regent': (['freeze', 'command'], [], (0.5, 0.2, 0.3, 0.2)),
    'Bitch': (['minions'], [], (1.2, 0.6, 0.8, 0.4)),
    'Skitter': (['swarm', 'insight'], [], (0.9, 0.3, 0.3, 0.3)),
    'Coil': (['insight'], ['reroll', 'precog'], (0.6, 0.5, 0.3, 0.3)),
    'Faultline': (['smash', 'area'], [], (1.1, 0.5, 0.5, 0.4)),
    'Newter': (['freeze'], ['fast'], (0.6, 0.4, 1.2, 0.3)),
    'Gregor the Snail': (['blast', 'freeze'], ['tough'], (0.9, 0.8, 0.1, 0.8)),
    'Labyrinth': (['area', 'shield', 'freeze'], [], (0.7, 0.9, 0.1, 0.2)),
    'Spitfire': (['blast', 'area'], [], (1.2, 0.2, 0.3, 0.2)),
    'Über': (['smash', 'insight'], ['fast'], (1.0, 0.5, 0.6, 0.4)),
    'Leet': (['craft', 'blast'], [], (0.8, 0.3, 0.4, 0.3)),
    'Circus': (['blast', 'vanish', 'blink'], ['precog'], (1.0, 0.4, 0.9, 0.3)),
    'Trainwreck': (['smash', 'craft'], ['tough'], (1.1, 1.2, 0.3, 1.0)),
    'Parian': (['minions'], [], (0.9, 0.7, 0.2, 0.2)),
    'Chariot': (['craft', 'blink'], [], (0.5, 0.4, 1.2, 0.3)),
    'Dinah Alcott': (['insight'], ['precog'], (0.0, 0.1, 0.1, 0.1)),
    'Trickster': (['blink', 'freeze'], [], (0.5, 0.4, 1.2, 0.3)),
    'Sundancer': (['area', 'blast'], [], (1.6, 0.4, 0.2, 0.3)),
    'Ballistic': (['blast', 'area'], [], (1.5, 0.3, 0.3, 0.3)),
    'Genesis': (['morph', 'minions'], ['tough'], (1.0, 1.0, 0.4, 0.8)),
    'Chubster': (['smash'], ['tough'], (0.6, 1.2, 0.1, 1.0)),
}
